Clean architecture
go-park-mail-ru/2022_2_Technopanki pull request #12
Opened 2022-10-16 20:27 UTC by Zuhropenchik

2022-10-17 07:01 UTC, somnevaetsya requested changes
Отличное начало, но есть небольшие замечания

2022-10-17 07:01 UTC, somnevaetsya commented on pkg/repository/postges.go
> +	gormDB, gormErr := gorm.Open(postgres.New(postgres.Config{
Можно же просто через gorm.Open(postgres.Open(вот тут строка для подключения))

2022-10-18 19:33 UTC, somnevaetsya requested changes

2022-10-18 19:33 UTC, somnevaetsya commented on internal/repository/repository.go
> +	Cfg               *configs.Config
Указатель на конфиг подразумевает, что мы будем что-то менять в этом объекте. Возникают два вопроса: зачем и что?)

2022-10-18 19:33 UTC, somnevaetsya commented on internal/usecases/usecase.go
> +	Cfg     *configs.Config
Указатель

2022-10-18 19:33 UTC, somnevaetsya commented on internal/usecases/user.go
> +package usecases
done

2022-10-18 19:33 UTC, somnevaetsya commented on pkg/repository/postgres.go
> +var DB *gorm.DB
Глобальная переменная, которая еще и импортируется?

2022-10-18 19:33 UTC, somnevaetsya commented on pkg/repository/postgres.go
> +type DBConfig struct {
Как раньше и писал, давай закинем в один конфиг, просто сделаем дополнительной структурой в пакете парсинга конфига

2022-10-18 19:33 UTC, somnevaetsya commented on pkg/repository/postgres.go
> +	//db, err := gorm.Open(postgres.Open("postgres://jobflowAdmin:12345@jfPostgres:5432/jobflowDB?sslmode=disable"), &gorm.Config{})
Убираем комментарии

2022-10-18 19:33 UTC, somnevaetsya commented on pkg/repository/postgres.go
> +func Connect(cfg DBConfig) error {
Вот такая штука лучше бы возвращала экземпляр бд, который мы бы прокидывали в репозитории при создании

2022-10-18 19:33 UTC, somnevaetsya commented on internal/usecases/user.go
> +	return token, us.ur.CreateUser(input)
Давай может отдельно вызовем, чтобы не возвращать токен при ошибке?

2022-10-18 19:33 UTC, somnevaetsya commented on internal/usecases/user.go
> +	input.ID = uuid.NewString()
Давай это сделаем после получения юзера, чтобы лишний раз при возникновении ошибки не делать это

2022-10-18 19:33 UTC, somnevaetsya commented on internal/usecases/user.go
> +	if err == nil {
А может будем проверять, что пользователь не пустой вернулся?

2022-10-18 19:33 UTC, somnevaetsya commented on internal/usecases/user.go
> +	inputValidity := validation.IsUserValidate(input)
Может isValid?

2022-10-18 19:33 UTC, somnevaetsya commented on internal/usecases/usecase.go
> +		Cfg:  repos.Cfg,
Нам тут нужен конфиг?

2022-10-18 19:33 UTC, somnevaetsya commented on internal/storage/users_test.go
> +//
Пока закрою глаза, но так не надо

2022-10-18 19:33 UTC, somnevaetsya commented on internal/repository/user.go
> +	return nil
Когда?

2022-10-18 19:33 UTC, somnevaetsya commented on internal/repository/repository.go
> +		UserRepository: NewUserPostgres(db),
done

2022-10-18 19:33 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +type UserH interface {
Интерфейсы не особо нужны, потому что мокать хендлеры не надо будет, но если так нравится, то я не против

2022-10-20 18:37 UTC, somnevaetsya requested changes
Немного осталось)

2022-10-20 18:37 UTC, somnevaetsya commented on .gitignore
> +data/
Пустая строка)

2022-10-20 18:37 UTC, somnevaetsya commented on cmd/main.go
> +		log.Fatal(configErr.Error())
??

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/userAccount.go
> +	Vacancies              []Vacancy         `json:"vacancies" gorm:"foreignKey:PostedByUserId;constraint:OnDelete:CASCADE;"`
Разве нельзя использовать Id юзера?

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/userAccount.go
> +	Resumes                []Resume          `json:"resumes" gorm:"foreignKey:UserAccountId;constraint:OnDelete:CASCADE;"`
Почему бы не использовать Id юзера?

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/userAccount.go
> +	VacancyActivities      []VacancyActivity `json:"vacancy_activities" gorm:"foreignKey:UserAccountId;constraint:OnDelete:CASCADE;"`
Id?

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/jobLocation.go
> +	Vacancies     []Vacancy `json:"vacancies" gorm:"foreignKey:JobLocationId;constraint:OnDelete:CASCADE;"`
Где поле JobLocationId?

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/vacancy.go
> +	VacancyActivities []VacancyActivity `json:"vacancyActivities" gorm:"foreignKey:VacancyId;constraint:OnDelete:CASCADE;"`
Тут используется Id

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/user.go
>  type User struct {
А этот юзер зачем?

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/vacancy.go
> +	ID            int       `json:"-" gorm:"primary_key"`
Эта вакансия зачем?

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +type UserH interface {
done

2022-10-20 18:37 UTC, somnevaetsya commented on Dockerfile
> +CMD ["./main"]
done

2022-10-20 18:37 UTC, somnevaetsya commented on cmd/main.go
> +type Database struct {
done

2022-10-20 18:37 UTC, somnevaetsya commented on cmd/main.go
> +	runErr := router.Run(viper.GetString("port"))
done

2022-10-20 18:37 UTC, somnevaetsya commented on cmd/main.go
> +func initConfig() error {
done

2022-10-20 18:37 UTC, somnevaetsya commented on docker-compose.yml
> +      -  '9000:5432'
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	user, err := storage.UserStorage.GetUserByEmail(input.Email)
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	c.SetCookie("session", token, int(sessions.SessionsStore.DefaultExpiresAt), "/", viper.GetString("domain"), false, true)
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	c.SetCookie("session", token, -1, "/", viper.GetString("domain"), false, true)
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +func NewHandler(usecases *usecases.UseCases) *Handler {
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	token, err := h.uc.User.SignIn(&input)
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, int(sessions.SessionsStore.DefaultExpiresAt), "/", viper.GetString("domain"), false, true)
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, int(sessions.SessionsStore.DefaultExpiresAt), "/", viper.GetString("domain"), false, true)
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, -1, "/", viper.GetString("domain"), false, true)
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	user, err := h.uc.User.AuthCheck(email.(string))
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/repository/user.go
> +type UserRepository interface {
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/usecases/user.go
> +	inputValidity := validation.IsValidate(input)
done

2022-10-20 18:37 UTC, somnevaetsya commented on pkg/repository/postges.go
> +package repository
done

2022-10-20 18:37 UTC, somnevaetsya commented on pkg/repository/postges.go
> +type Config struct {
done

2022-10-20 18:37 UTC, somnevaetsya commented on pkg/repository/postges.go
> +	gormDB, gormErr := gorm.Open(postgres.New(postgres.Config{
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/usecases/usecase.go
> +	Cfg     *configs.Config
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/usecases/usecase.go
> +		Cfg:  repos.Cfg,
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/storage/users_test.go
> +//
done

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/resume.go
> +	ID               uint             `json:"id" gorm:"primaryKey;autoIncrement;"`
PrimaryKey автоинкремент по дефолту

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/resume.go
> +	ApplicantSkills  []Skill          `json:"applicant_skills" gorm:"many2many:resume_skills;"`
Если мы тут указали таблице resume_skills в качестве many2many, то и в другой записи надо указать gorm:"many2many:resume_skills;"`

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/userAccount.go
> +	ID                     uint              `json:"id" gorm:"primaryKey;autoIncrement;"`
Автоинкремент по дефолту

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/Models/vacancy.go
> +	Skills            []Skill           `json:"skills" gorm:"many2many:vacancy_skills;"`
Это отношение надо отразить и в другой модели

2022-10-20 18:37 UTC, somnevaetsya commented on internal/entity/resume.go
> +	Description string
А где остальное?

2022-10-20 18:37 UTC, somnevaetsya commented on internal/network/sessions/store.go
> +	DefaultExpiresAt: 12 * time.Hour / time.Second,
В конфиг

2022-10-21 18:03 UTC, AkimEgorov commented on internal/entity/Models/userAccount.go
> +	Vacancies              []Vacancy         `json:"vacancies" gorm:"foreignKey:PostedByUserId;constraint:OnDelete:CASCADE;"`
Id юзера как раз и используется. Внешние ключи полей UserAccountId, PostedByUserId таблицы Resume и Vacancy соответственно указывают на поле Id таблицы userAccount

2022-10-21 18:04 UTC, AkimEgorov commented on internal/entity/Models/userAccount.go
> +	Resumes                []Resume          `json:"resumes" gorm:"foreignKey:UserAccountId;constraint:OnDelete:CASCADE;"`
Id юзера как раз и используется. Ситуация такая же, как в сообщении выше

2022-10-21 18:04 UTC, AkimEgorov commented on internal/entity/Models/userAccount.go
> +	VacancyActivities      []VacancyActivity `json:"vacancy_activities" gorm:"foreignKey:UserAccountId;constraint:OnDelete:CASCADE;"`
Id юзера как раз и используется. Ситуация такая же, как в сообщении выше

2022-10-21 18:05 UTC, AkimEgorov commented on internal/entity/Models/jobLocation.go
> +	Vacancies     []Vacancy `json:"vacancies" gorm:"foreignKey:JobLocationId;constraint:OnDelete:CASCADE;"`
В таблице Vacancy

2022-10-21 18:07 UTC, AkimEgorov commented on internal/entity/Models/vacancy.go
> +	VacancyActivities []VacancyActivity `json:"vacancyActivities" gorm:"foreignKey:VacancyId;constraint:OnDelete:CASCADE;"`
Так точно)

2022-10-21 18:12 UTC, AkimEgorov commented on internal/entity/Models/resume.go
> +	ApplicantSkills  []Skill          `json:"applicant_skills" gorm:"many2many:resume_skills;"`
Необязательно. Достаточно указать связь many2many только в одной таблице и вспомогательная таблица сгенерируется

2022-10-21 18:13 UTC, AkimEgorov commented on internal/entity/Models/vacancy.go
> +	Skills            []Skill           `json:"skills" gorm:"many2many:vacancy_skills;"`
Необязательно. Вспомогательная таблица создается и так

2022-10-21 18:18 UTC, AkimEgorov commented on internal/entity/vacancy.go
> +	ID            int       `json:"-" gorm:"primary_key"`
Ситуация та же, что и моделью User

2022-10-21 18:19 UTC, AkimEgorov approved these changes

2022-10-21 18:58 UTC, VladislavKirpichov approved these changes

2022-10-22 12:04 UTC, somnevaetsya requested changes

2022-10-23 19:20 UTC, somnevaetsya approved these changes

2022-10-23 19:21 UTC, merged