2.13 session repository
go-park-mail-ru/2022_2_Technopanki pull request #15
Opened 2022-10-23 19:24 UTC by Zuhropenchik

2022-10-25 11:29 UTC, somnevaetsya requested changes

2022-10-25 11:29 UTC, somnevaetsya commented on configs/config.go
> +type RedisConfig struct {
Когда конфиг нормальный выйдет?

2022-10-25 11:29 UTC, somnevaetsya commented on internal/entity/Models/resume.go
> +	ID               uint             `json:"id" gorm:"primaryKey;autoIncrement;"`
Привет)

2022-10-25 11:29 UTC, somnevaetsya commented on internal/entity/Models/skill.go
> +	ID        uint   `json:"id" gorm:"primaryKey;autoIncrement"`
Привет)

2022-10-25 11:29 UTC, somnevaetsya commented on internal/entity/Models/userAccount.go
> +	UUID                   string            `json:"-"` //TODO убрать
А это нам зачем нужно?

2022-10-25 11:29 UTC, somnevaetsya commented on internal/network/middleware/session.go
> +	userSession, err := sm.sr.GetSession(session.Token(sessionToken))
Дальше мы в контекст проставляем userSession по ключу userEmail. Где-то скрыт обман

2022-10-25 11:29 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +		SessionMiddleware: middleware.NewSessionMiddleware(_sr),
Почему у нас мидлварь стала внутри хендлеров?

2022-10-25 11:29 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, int(uh.sr.Expiring()), "/", uh.cfg.Domain, false, true)
uh.sr - нейминг ужасный, ничего не понять

2022-10-25 11:29 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	"HeadHunter/internal/entity/Models"
Название пакета с большой буквы?

2022-10-25 11:29 UTC, somnevaetsya commented on internal/repository/session/store.go
> -package sessions
Ничего не понял, если мы подвязали уже редис, то зачем нам вот это?

2022-10-25 11:29 UTC, somnevaetsya commented on internal/usecases/user.go
> +	input.UUID = uuid.NewString()
Зачем нам вот это нужно?

2022-10-25 11:29 UTC, somnevaetsya commented on pkg/repository/redis.go
>  package repository
Почему это не лежит вместе со всем редисом?

2022-10-25 22:37 UTC, Zuhropenchik commented on internal/entity/Models/userAccount.go
> +	UUID                   string            `json:"-"` //TODO убрать
Пока юзер-репозиторий не заработает, эта штука для хранилища в мапе нужна

2022-10-25 22:39 UTC, Zuhropenchik commented on pkg/repository/redis.go
>  package repository
Ну так в internal лежит логика для конкретно нашего приложения, а в pkg та, которая может переиспользоваться.  RedisConnect спокойно можно использовать в любом другом проекте

2022-10-25 22:39 UTC, Zuhropenchik commented on internal/usecases/user.go
> +	input.UUID = uuid.NewString()
Временные издержки, пока юзер репозиторий не заработает

2022-10-29 13:56 UTC, somnevaetsya commented on internal/entity/Models/userAccount.go
> +	UUID                   string            `json:"-"` //TODO убрать
Почему мы в майе не можем по Id хранить?

2022-10-29 13:57 UTC, somnevaetsya commented on internal/usecases/user.go
> +	input.UUID = uuid.NewString()
Почему обычный Id не устраивает?

2022-10-29 13:58 UTC, somnevaetsya commented on pkg/repository/redis.go
>  package repository
Благодаря такой логике, я ничего не понял, когда смотрел код

2022-10-29 14:09 UTC, somnevaetsya requested changes
Гуд

2022-10-29 14:09 UTC, somnevaetsya commented on configs/config.go
> +	yamlFile, yamlErr := ioutil.ReadFile(filename)
Данный метод уже deprecated, не пойдет

2022-10-29 14:09 UTC, somnevaetsya commented on configs/config.go
> +	filename, fileErr := filepath.Abs("./configs/config.yml")
Нет обработки ошибки

2022-10-29 14:09 UTC, somnevaetsya commented on configs/config.go
> +	marshalErr := yaml.Unmarshal(yamlFile, config)
Отличное решение, только выше надо немного поправить

2022-10-29 14:09 UTC, somnevaetsya commented on docker-compose.yml
> +    command: >
А вот эта штучка зачем?)

2022-10-29 14:09 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +		if len([]rune(user.ApplicantName)) > 20 || len([]rune(user.ApplicantName)) < 3 {
Магические числа...

2022-10-29 14:09 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +		if len([]rune(user.ApplicantSurname)) > 20 || len([]rune(user.ApplicantSurname)) < 3 {
Магия...

2022-10-29 14:09 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +		if len([]rune(user.CompanyName)) > 20 || len([]rune(user.CompanyName)) < 2 {
Там было 3... тут стало 2...

2022-10-29 14:09 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	var input = models.UserAccount{}
Разве IDE не подсказывает, что = не нужно?

2022-10-29 14:09 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, int(uh.sessionRepos.Expiring()), "/", uh.cfg.Domain, false, true)
У нас внутри хендлера лежит конфиг, поле не приватное, зачем нам обвязка лишняя?

2022-10-29 14:09 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, int(uh.sessionRepos.Expiring()), "/", uh.cfg.Domain, false, true)
Я бы все поля вынес в конфиг (про false и true)

2022-10-29 14:09 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	User         usecases.User
И зачем нам юзкейс публичным делать? Почему бы сразу не назвать userUsecase?

2022-10-29 14:09 UTC, somnevaetsya commented on internal/network/middleware/session.go
> +	userEmail, err := sm.sr.GetSession(session.Token(sessionToken))
sm.sr - я ничего в этом не понимаю, давай, пожалуйста, не сокращать

2022-10-29 14:09 UTC, somnevaetsya commented on internal/repository/session/redis.go
> +		return "", err
Нет обвязки над ошибкой, может, что-то придумаем?

2022-10-29 14:09 UTC, somnevaetsya commented on internal/usecases/user.go
> +	if user.UserType == "applicant" {
Скорее всего, вот такая логика будет часто встречаться, предлагаю сделать функцию, которая в зависимости от типа будет заполнять модельку

2022-10-29 14:10 UTC, somnevaetsya commented on internal/repository/session/store.go
> -package sessions
done

2022-10-29 14:10 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	"HeadHunter/internal/entity/Models"
done

2022-10-29 14:10 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, int(uh.sr.Expiring()), "/", uh.cfg.Domain, false, true)
Не изменилось

2022-10-29 14:10 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +		SessionMiddleware: middleware.NewSessionMiddleware(_sr),
done

2022-10-29 14:10 UTC, somnevaetsya commented on internal/network/middleware/session.go
> +	userSession, err := sm.sr.GetSession(session.Token(sessionToken))
done

2022-10-29 14:11 UTC, somnevaetsya commented on configs/config.go
> +type RedisConfig struct {
done

2022-10-29 14:11 UTC, somnevaetsya commented on internal/entity/Models/resume.go
> +	ID               uint             `json:"id" gorm:"primaryKey;autoIncrement;"`
done

2022-10-29 14:11 UTC, somnevaetsya commented on internal/entity/Models/skill.go
> +	ID        uint   `json:"id" gorm:"primaryKey;autoIncrement"`
done

2022-10-29 15:30 UTC, Zuhropenchik commented on docker-compose.yml
> +    command: >
Пароль

2022-10-31 06:22 UTC, somnevaetsya commented on cmd/main.go
> +	sessions := session.NewRedisStore(mainConfig, client)
done

2022-10-31 06:23 UTC, somnevaetsya commented on configs/config.go
> +	yamlFile, yamlErr := ioutil.ReadFile(filename)
Не исправлено

2022-10-31 06:23 UTC, somnevaetsya commented on configs/config.go
> +	filename, fileErr := filepath.Abs("./configs/config.yml")
done

2022-10-31 06:25 UTC, somnevaetsya commented on configs/config.go
> +	marshalErr := yaml.Unmarshal(yamlFile, config)
done

2022-10-31 06:25 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +		if len([]rune(user.ApplicantName)) > 20 || len([]rune(user.ApplicantName)) < 3 {
done

2022-10-31 06:25 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +		if len([]rune(user.ApplicantSurname)) > 20 || len([]rune(user.ApplicantSurname)) < 3 {
done

2022-10-31 06:25 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +		if len([]rune(user.CompanyName)) > 20 || len([]rune(user.CompanyName)) < 2 {
done

2022-10-31 06:25 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	var input = models.UserAccount{}
done

2022-10-31 06:25 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, int(uh.sessionRepos.Expiring()), "/", uh.cfg.Domain, false, true)
Обвязка осталась

2022-10-31 06:26 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	User         usecases.User
done

2022-10-31 06:26 UTC, somnevaetsya commented on internal/network/middleware/session.go
> +	userEmail, err := sm.sr.GetSession(session.Token(sessionToken))
done

2022-10-31 06:28 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	sessionRepos session.Repository
sessionRepo

2022-10-31 06:28 UTC, somnevaetsya commented on internal/usecases/user.go
> +	input.UUID = uuid.NewString()
?

2022-10-31 06:28 UTC, somnevaetsya commented on internal/usecases/user.go
> +	if user.UserType == "applicant" {
done

2022-10-31 06:29 UTC, somnevaetsya commented on internal/entity/utils/user.go
> +func GetName(user, reference *models.UserAccount) error {
Можно было бы назвать иначе, по типу, FillUser

2022-10-31 06:29 UTC, somnevaetsya commented on internal/repository/session/redis.go
> +		return "", err
done

2022-10-31 06:45 UTC, somnevaetsya commented on configs/config.yml
> +validation:
Цифры повторяется, может как-нибудь объединим?

2022-10-31 06:45 UTC, somnevaetsya commented on internal/repository/session/redis.go
> +		return "", errorHandler.ErrCannotCreateSession
В редисе все ошибки будут возвращаться с кодом 500, может мы будем прост опрокидывать оригинальную ошибку `err` с помощью `fmt.Errorf("Error occured in CreateSession: %w")`? Она все равно конвертится будет в 500. В других случаях так же, как и здесь

2022-10-31 06:45 UTC, somnevaetsya commented on configs/config.go
> +	marshalErr := yaml.Unmarshal(yamlFile, config)
done

2022-10-31 12:43 UTC, Zuhropenchik commented on internal/usecases/user.go
> +	input.UUID = uuid.NewString()
Учел в другом пр

2022-11-01 06:31 UTC, somnevaetsya commented on configs/config.yml
> +validation:
done

2022-11-01 06:31 UTC, somnevaetsya commented on internal/repository/session/redis.go
> +		return "", errorHandler.ErrCannotCreateSession
done

2022-11-01 06:36 UTC, somnevaetsya requested changes
Финишная прямая

2022-11-01 06:36 UTC, somnevaetsya commented on internal/repository/session/redis.go
> +		return "", errorHandler.ErrSessionNotFound
А может другая ошибка будет? Давай вернем через Errorf на всякий

2022-11-01 06:36 UTC, somnevaetsya commented on internal/usecases/user.go
> +	token, newSessionErr := us.sr.NewSession(input.Email)
Почему опять sr?)

2022-11-01 06:36 UTC, somnevaetsya commented on pkg/repository/redis.go
> +		DB:       0,
Почему нуль не в константах?

2022-11-01 06:36 UTC, somnevaetsya commented on pkg/repository/redis.go
> +		DB:       0,
Он вообще нужен?

2022-11-01 06:36 UTC, somnevaetsya commented on pkg/repository/redis.go
> +	address := fmt.Sprintf("%s:%s", cfg.Host, cfg.Port)
Можно сразу в поле вставить, эта переменная не будет больше использоваться

2022-11-01 06:36 UTC, somnevaetsya commented on internal/entity/utils/user.go
> +func GetName(user, reference *models.UserAccount) error {
done

2022-11-01 06:36 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	sessionRepos session.Repository
done

2022-11-01 06:36 UTC, somnevaetsya commented on configs/config.go
> +	yamlFile, yamlErr := ioutil.ReadFile(filename)
done

2022-11-01 06:36 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.SetCookie("session", token, int(uh.sr.Expiring()), "/", uh.cfg.Domain, false, true)
done

2022-11-01 06:37 UTC, somnevaetsya requested changes

2022-11-01 06:37 UTC, somnevaetsya commented on configs/config.go
> +	DefaultExpiringSession int64            `yaml:"defaultExpiringSession"`
Почему не просто int или не uint? В куке преобразуешь именно к int

2022-11-01 14:34 UTC, somnevaetsya commented on internal/repository/session/redis.go
> +		return "", errorHandler.ErrSessionNotFound
done

2022-11-01 14:35 UTC, somnevaetsya commented on internal/usecases/user.go
> +	token, newSessionErr := us.sr.NewSession(input.Email)
done

2022-11-01 14:35 UTC, somnevaetsya commented on pkg/repository/redis.go
> +		DB:       0,
done

2022-11-01 14:36 UTC, somnevaetsya commented on pkg/repository/redis.go
> +	address := fmt.Sprintf("%s:%s", cfg.Host, cfg.Port)
done

2022-11-01 14:56 UTC, somnevaetsya approved these changes

2022-11-01 14:57 UTC, VladislavKirpichov approved these changes

2022-11-01 14:58 UTC, AkimEgorov approved these changes

2022-11-01 14:58 UTC, somnevaetsya commented on configs/config.go
> +	DefaultExpiringSession int64            `yaml:"defaultExpiringSession"`
done

2022-11-01 14:58 UTC, merged