User Repository
go-park-mail-ru/2022_2_Technopanki pull request #16
Opened 2022-10-28 11:12 UTC by Zuhropenchik

2022-10-29 14:34 UTC, somnevaetsya requested changes
C указателями намудрил, его можно везде прокидывать, чтобы не копировать лишний раз, не бойся их)

2022-10-29 14:34 UTC, somnevaetsya commented on cmd/main.go
> +		UserRepository: repository.NewUserPostgres(db)}, //TODO добавить нормальнуб бд
Вполне вероятно, что репозиторий юзера мы где-то еще будем использовать, поэтому предлагаю создать под него переменную

2022-10-29 14:34 UTC, somnevaetsya commented on internal/repository/user.go
> +var COST = 10
В конфиг

2022-10-29 14:34 UTC, somnevaetsya commented on internal/repository/user.go
> +	encryptedPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), COST)
Давай вынесем это в utils и сделаем обертку, которая сразу будет нам стригу возвращать

2022-10-29 14:34 UTC, somnevaetsya commented on internal/repository/user.go
> +	encryptedPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), COST)
Это кстати логика юзкейса, тут только создание должно быть

2022-10-29 14:34 UTC, somnevaetsya commented on internal/repository/user.go
> +		return nil, query.Error
А может завернем во что-нибудь? Чтобы не так некрасиво смотрелось

2022-10-29 14:34 UTC, somnevaetsya commented on internal/storage/users.go
>  package storage
Пора выпиливать

2022-10-29 14:34 UTC, somnevaetsya commented on internal/usecases/user.go
> +	if cryptErr := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password)); cryptErr != nil {
Тоже предлагаю сделать функцию проверки пароля, будет аккуратнее выглядеть

2022-10-29 14:34 UTC, somnevaetsya commented on internal/usecases/user.go
> +	fmt.Println(user)
Отладочную печать убираем

2022-10-29 14:34 UTC, somnevaetsya commented on internal/usecases/user.go
>  		return "", errorHandler.ErrServiceUnavailable
Я бы все-таки прокинул ошибку наверх, но как-нибудь бы дописал, что случилась ошибка в репозитории, получите - распишитесь

2022-10-29 14:34 UTC, somnevaetsya commented on internal/usecases/user.go
>  		return "", errorHandler.ErrServiceUnavailable
Тогда в репозитории никак оборачивать не надо

2022-10-29 14:34 UTC, somnevaetsya commented on internal/usecases/user.go
> +func (us *UserService) AuthCheck(email string) (models.UserAccount, error) {
Почему бы не вернуть указатель?

2022-10-29 14:34 UTC, somnevaetsya commented on internal/usecases/user.go
> +	inputValidity := validation.IsUserValid(*input)
Почему бы не принять указатель?

2022-10-29 14:34 UTC, somnevaetsya commented on internal/usecases/user.go
>  	inputValidity := validation.IsAuthDataValid(*input)
Почему бы не принять указатель?

2022-10-31 06:48 UTC, somnevaetsya commented on cmd/main.go
> +	PostgresRepository := repository.NewPostgresRepository(db)
А зачем с большой буквы?

2022-10-31 06:48 UTC, somnevaetsya commented on cmd/main.go
> +		UserRepository: repository.NewUserPostgres(db)}, //TODO добавить нормальнуб бд
done

2022-10-31 06:48 UTC, somnevaetsya commented on internal/repository/user.go
> +var COST = 10
done

2022-10-31 07:08 UTC, somnevaetsya commented on internal/repository/user.go
> +	encryptedPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), COST)
done

2022-10-31 07:08 UTC, somnevaetsya commented on internal/repository/user.go
> +		return nil, query.Error
done

2022-10-31 07:08 UTC, somnevaetsya commented on internal/storage/users.go
>  package storage
done

2022-10-31 07:08 UTC, somnevaetsya commented on internal/usecases/user.go
> +	if cryptErr := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password)); cryptErr != nil {
done

2022-10-31 07:08 UTC, somnevaetsya commented on internal/usecases/user.go
> +	fmt.Println(user)
done

2022-10-31 07:09 UTC, somnevaetsya commented on internal/usecases/user.go
>  		return "", errorHandler.ErrServiceUnavailable
done

2022-10-31 07:13 UTC, somnevaetsya commented on internal/usecases/user.go
> +		return "", errorHandler.ErrCannotCreateUser
Необязательно делать свою ошибку, можно просто обернуть ее с помощью fmt.Errorf("Error occured in CreateUser: %w"). Все равно 500 будем возвращать, а тут еще и пояснение, где случилось и что случилось

2022-10-31 07:13 UTC, somnevaetsya commented on internal/usecases/user.go
> +	} //TODO придумать более строгую валидацию
Да, я про это написал в репозитории

2022-10-31 07:13 UTC, somnevaetsya commented on internal/usecases/user.go
> +	} //TODO придумать более строгую валидацию
Ну и явно надо проверить пароли

2022-10-31 07:13 UTC, somnevaetsya commented on internal/usecases/user.go
> +	safeFields := []string{"email", "user_type", "contact_number", "description", "date_of_birth",
Может в константы? И нужно ли это вообще

2022-10-31 07:13 UTC, somnevaetsya commented on internal/usecases/user.go
> +func (us *UserService) AuthCheck(email string) (models.UserAccount, error) {
done

2022-10-31 07:13 UTC, somnevaetsya commented on internal/usecases/user.go
>  	inputValidity := validation.IsAuthDataValid(*input)
done

2022-10-31 07:13 UTC, somnevaetsya requested changes
Движемся в верном направлении, но медленно

2022-11-01 06:38 UTC, somnevaetsya commented on internal/usecases/user.go
> +	inputValidity := validation.IsUserValid(*input)
done

2022-11-01 06:56 UTC, somnevaetsya commented on cmd/main.go
> +	PostgresRepository := repository.NewPostgresRepository(db)
done

2022-11-01 06:56 UTC, somnevaetsya commented on docker-compose.yml
> +      --requirepass rjf358123QWE
Пустая строка)

2022-11-01 06:56 UTC, somnevaetsya commented on configs/config.yml
> +  defaultApplicantAvatar: "basic_applicant_avatar"
done

2022-11-01 06:58 UTC, somnevaetsya commented on internal/entity/constants/user.go
> +package constants
Пакет константы, но почему-то объявляем переменные через var)

2022-11-01 06:58 UTC, somnevaetsya commented on internal/entity/utils/crypt.go
> +		return errorHandler.ErrUnauthorized
Bad request, не?

2022-11-01 06:58 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +	GetUserImage(c *gin.Context)
done

2022-11-01 06:58 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	c.Status(http.StatusOK)
done

2022-11-01 07:04 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	}
У нас этот кусок кода постоянно повторяется, замутим функцию?

2022-11-01 07:04 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	for key := range form.File {
Не особо мне такое нравится, где украл?

2022-11-01 07:04 UTC, somnevaetsya commented on internal/repository/repository.go
> +	GetUserSafety(id uint, safeFields []string) (*models.UserAccount, error)
?

2022-11-01 07:04 UTC, somnevaetsya commented on internal/repository/user.go
> +func queryUserValidation(query *gorm.DB) error {
done

2022-11-01 07:04 UTC, somnevaetsya commented on internal/repository/user.go
> +	return up.db.Model(oldUser).Updates(newUser).Error
?

2022-11-01 07:04 UTC, somnevaetsya commented on internal/repository/user.go
> +func (up *UserPostgres) GetUserSafety(id uint, safeFields []string) (*models.UserAccount, error) {
done

2022-11-01 07:04 UTC, somnevaetsya commented on internal/usecases/user.go
> +	userRep    repository.UserRepository
done

2022-11-01 07:06 UTC, somnevaetsya commented on internal/usecases/user.go
> +	} //TODO придумать более строгую валидацию
?

2022-11-01 07:08 UTC, somnevaetsya requested changes

2022-11-01 07:08 UTC, somnevaetsya commented on internal/usecases/user.go
> +	if user.Image == fmt.Sprintf("basic_%s_avatar.webp", user.UserType) || user.Image == "" {
Почему если дефолтная картинка, то мы вдруг ее заменяем?

2022-11-01 07:40 UTC, Zuhropenchik commented on internal/usecases/user.go
> +	if user.Image == fmt.Sprintf("basic_%s_avatar.webp", user.UserType) || user.Image == "" {
Если у человека стоит дефолт аватарка ( как фотик в вк), то значит у него нет аватарки и надо создать новую.

2022-11-01 07:40 UTC, Zuhropenchik commented on internal/usecases/user.go
> +	if user.Image == fmt.Sprintf("basic_%s_avatar.webp", user.UserType) || user.Image == "" {
Я сделал, что при регистрации автоматом присваивается default фотка

2022-11-01 16:50 UTC, Zuhropenchik commented on internal/entity/utils/crypt.go
> +		return errorHandler.ErrUnauthorized
Придумал вариант еще лучше

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/constants/user.go
> +package constants
done

2022-11-05 11:55 UTC, somnevaetsya commented on docker-compose.yml
> +      --requirepass rjf358123QWE
done

2022-11-05 12:16 UTC, somnevaetsya requested changes
По идее аватарки должны работать, но слишком все надекомпозировано, собери хоть чуть-чуть в кучу, отсмотрю еще раз. Замечания есть

2022-11-05 12:16 UTC, somnevaetsya commented on internal/entity/utils/crypt.go
> +		return errorHandler.ErrWrongAnswer
Кто такой WrongAnswer? BadRequest

2022-11-05 12:16 UTC, somnevaetsya commented on internal/entity/utils/user.go
>  func FillUser(user, reference *models.UserAccount) error {
А если поля новые пустые, то мы перетрем старые нормальные поля на новые пустые. Может сразу будем чекать на пустую строку? Потом сможем использовать в рефакторе пользователя

2022-11-05 12:16 UTC, somnevaetsya commented on internal/entity/vacancy.go
> +	EmployerName  string    `json:"image"`
Заработался уже конкретно

2022-11-05 12:16 UTC, somnevaetsya commented on internal/errorHandler/complexError.go
> +package errorHandler
Я вообще этого прикола не понял, хочу объяснений

2022-11-05 12:16 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +func (uh *UserHandler) getEmailFromContext(c *gin.Context) (string, error) {
Ну по факту это же не хендлер, почему мы к хендлеру привязываем эту функцию? Можно сделать ее приватной в пакете, но по факту это же не хендлер, мы не используем поля хендлера, ничего не делаем

2022-11-05 12:16 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	response.SendSuccessData(&input, c)
Это что за новый прикол? Почему cJSON не используется?

2022-11-05 12:16 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	response.SendPreviewData(user, c)
Это кто такой?

2022-11-05 12:16 UTC, somnevaetsya commented on internal/network/middleware/errorHandler.go
> +			response.SendErrorData(rawErr.Err.(*errorHandler.ComplexError), c)
Мама дорогая, зачем?

2022-11-05 12:16 UTC, somnevaetsya commented on internal/network/response/user.go
> +func SendPreviewData(user *models.UserAccount, c *gin.Context) {
Кто такой статус?

2022-11-05 12:16 UTC, somnevaetsya commented on internal/repository/images/user.go
> +	fullPath := strings.Join([]string{cfg.Path, "avatar/"}, "")
А вдруг пустая строка? Есть проверка на это?

2022-11-05 12:16 UTC, somnevaetsya commented on internal/usecases/user.go
> +	switch imageExt {
Можно не использовать под конкретный тип определенный Decode

2022-11-05 12:16 UTC, somnevaetsya commented on internal/usecases/user.go
> +	switch imageExt {
Просто image.Decode

2022-11-05 12:16 UTC, somnevaetsya commented on pkg/repository/webp.go
> +func UploadWebpImage(path, name string, image *image.Image) (err error) {
Как-то все раскидано не пойми куда и что, не особо круто. Я бы немного собрал все, хотя бы чуть-чуть

2022-11-22 19:56 UTC, closed without merging