Vacancy handler
go-park-mail-ru/2022_2_Technopanki pull request #19
Opened 2022-11-01 13:47 UTC by AkimEgorov

2022-11-02 15:07 UTC, Zuhropenchik requested changes

2022-11-02 15:07 UTC, Zuhropenchik commented on internal/entity/models/vacancy.go
> +func (u UpdateVacancy) Validate() error {
Указателей быть не должно + эту функцию можно в validation вынести

2022-11-03 16:44 UTC, Zuhropenchik reviewed
Заметил еще пару моментов..

2022-11-03 16:44 UTC, Zuhropenchik commented on internal/network/handlers/vacancy.go
> +func (vh *VacancyHandler) GetById(c *gin.Context) {
Этот метод не должен обращаться к конкретному пользователю (Скажу больше, в репозитории юзер айди даже не используется), поэтому брать айдиюзера не нужно.

2022-11-03 16:44 UTC, Zuhropenchik commented on internal/network/handlers/vacancy.go
> +func (vh *VacancyHandler) GetById(c *gin.Context) {
К тому же, просмотр вакансий это не приватная операция, поэтому тут вообще не нужно брать из контекста email (userEmail проставляется только если пользователь проходит проверку по сессиям)

2022-11-03 16:44 UTC, Zuhropenchik commented on internal/network/handlers/vacancy.go
> +func (vh *VacancyHandler) GetById(c *gin.Context) {
Вообще по поводу айдишника идея хорошая, было бы неплохо добавить еще один метод, который будет кидать все вакансии, принадлежащие определенному юзеру.

2022-11-04 10:21 UTC, Zuhropenchik requested changes

2022-11-04 10:21 UTC, Zuhropenchik commented on internal/network/handlers/vacancy.go
> +		_ = c.Error(errorHandler.ErrInvalidQuery)
Теперь это не Query, а Param лучше назвать, раз мы в итоге перешли на параметры

2022-11-04 10:21 UTC, Zuhropenchik commented on internal/network/handlers/vacancy.go
> +	c.JSON(http.StatusOK, map[string]interface{}{
Можно использоваться запить gin.H{}, которая по смыслу то же самое означает

2022-11-04 10:21 UTC, Zuhropenchik commented on internal/network/router.go
> +			vacancies.GET("/company/:id", h.VacancyHandler.GetUserVacancies, middleware.ErrorHandler())
Тут ожидается id в урле, а в самом хендлере вызываешь getUserId. Вместо getUserId лучше просто считывать параметр и по нему искать вакансии

2022-11-04 10:21 UTC, Zuhropenchik commented on internal/repository/vacancy.go
> +func (vp *VacancyPostgres) Update(userId uint, vacancyId int, vacancy *models.UpdateVacancy) error {
До сих пор кажется очень странным, что userId и vacancyId разных типов данных, лучше в handler сделать каст

2022-11-04 10:22 UTC, Zuhropenchik commented on internal/network/handlers/vacancy.go
> +		_ = c.Error(errorHandler.ErrInvalidId)
Теперь стоит переименовать на InvalidParam:)

2022-11-05 11:18 UTC, somnevaetsya commented on internal/network/router.go
> +			vacancies.DELETE("/:id", h.VacancyHandler.Delete, middleware.ErrorHandler())
Не именно свои, а только авторизованные пользователи могли что-то менять. И да, надо бы проверить, что вакансия была создана именно этим пользователем, проверять на уровне юзкейса

2022-11-05 11:22 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +		_ = c.Error(errorHandler.ErrInvalidId)
Мужики, глянул на GetUserId, возвращает только 0 в случае ошибки, а тут на ноль проверки нет, то есть мы никак не проверяем, успешно ли мы получили айдишник или нет

2022-11-05 11:23 UTC, somnevaetsya commented on internal/usecases/usecase.go
> +	Delete(uint, int) error
Согласен

2022-11-05 11:23 UTC, somnevaetsya commented on internal/usecases/usecase.go
> +	Delete(uint, int) error
Согласен

2022-11-05 11:24 UTC, somnevaetsya commented on internal/entity/models/vacancy.go
> +func (u UpdateVacancy) Validate() error {
Указатели могут быть, если мы используем либу validate. Но да, здесь они не нужны

2022-11-05 11:54 UTC, somnevaetsya requested changes
Надо влить юзера, потому что дифф грязный. Либо давай сделаем ребейс от ветки с юзером, а потом перенаправим мр в ту ветку, чтобы я видел. где свежие изменения

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/models/userAccount.go
> +	UUID                   string            `json:"-"` //TODO убрать
Можно убрать

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/models/vacancy.go
> +	Location          string            `json:"location" gorm:"not null;"`
Может можно null?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/models/vacancy.go
> +	Extra             string            `json:"extra" gorm:"not null"`
Extra?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/models/vacancy.go
>  type Vacancy struct {
Не совсем понятно, нужно ли действительно много новых полей?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/models/vacancy.go
> +type UpdateVacancy struct {
Можно же передавать в той же модели, что и обычная вакансия, просто поставить omitempty

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/models/vacancyActivity.go
>  type VacancyActivity struct {
Правильно понимаю, что это отклик?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +func verifyPassword(password string) bool {
Тут формат уехал почему-то

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +}
Нет пустой строки

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/validation/vacancy.go
> +func UpdateVacancyValidate(u models.UpdateVacancy) error {
Если все поля пустые, что довольно сложно провернуть. Странная валидация

2022-11-05 11:54 UTC, somnevaetsya commented on internal/entity/validation/vacancy.go
> +func QueryVacancyValidation(query *gorm.DB) error {
Уже была такая штука в юзере, предлагал сделать case, в зависимости от того, кого валидируем

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +		UserHandler:            newUserHandler(usecases, _cfg, _sr),
А нам действительно в одном хендлере нужен другой хендлер? Просто по факту хендлер занимается валидацией запроса и передачей данных в другие слои. Странно, что у нас другая ручка вызывается в этой ручке

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +		VacancyHandler:         newVacancyHandler(usecases, handlers),
Хендлер создается от хендлеров. Рекурсия?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +func (uh *UserHandler) GetUserId(c *gin.Context) uint {
Мне такая тема не особо нравится, потому что по факту это не хендлер, это функция получения юзера по входным данным, эти данные не передаются в ответ, поэтому и нельзя назвать хендлером. Я бы вынес ее в utils

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +		_ = c.Error(errorHandler.ErrUserNotExists)
Это не userNotExists, это InvalidArgument, потому что в бд мы не сходили

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/handlers/user.go
> +	emailString := userEmail.(string)
А вдруг не получилось? По факту, мы тут ловим панику

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +type getAllVacanciesResponce struct {
Можно не создавать структуру, просто сделать ее анонимной

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +	userId := vh.userHandler.GetUserId(c)
Как и писал выше, не надо хранить один хендлер в другом хендлере - получается не особо чисто, да и нам нужна только одна функция из всего хендлера. Кидаем ее в утилс и не паримся

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/handlers/vacancy_activity.go
> +type GetAllVacancyAppliesResponce struct {
У нас она импортируемая, но нужна ли так сильно на импорт? Нужна ли вообще?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/router.go
> +			vacancies.GET("/company/:id", h.VacancyHandler.GetUserVacancies, middleware.ErrorHandler())
Почему /company/:id, а хендлер getUserVacancies? Где-то я что-то упускаю...

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/router.go
> +			user.PUT("/", sessionMW.Session, h.UserHandler.UpgradeUser, middleware.ErrorHandler())
Немного не понял, а у нас на юзере больше ничего нет? Где аватарки и прочее?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/router.go
> +			vacancies.POST("/apply", sessionMW.Session, h.VacancyActivityHandler.ApplyForVacancy, middleware.ErrorHandler())
По факту группа у нас vacancies, но хендлер vacancyActivityHandler. Может объединим их?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/network/router.go
> +			vacancies.GET("/applies/:id", sessionMW.Session, h.VacancyActivityHandler.GetAllVacancyApplies, middleware.ErrorHandler())
Нужен еще хендлер на просмотр откликов пользователя

2022-11-05 11:54 UTC, somnevaetsya commented on internal/repository/vacancy.go
> +	return vacancies, validation.QueryVacancyValidation(query)
Немного не понял, а зачем валидируем?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/repository/vacancy.go
> +	vacancy.PostedByUserId = userId
В юзкейс, тут только бд

2022-11-05 11:54 UTC, somnevaetsya commented on internal/repository/vacancy.go
> +	query := vp.db.Where("posted_by_user_id = ?", userId).Find(&vacancies)
Работает?

2022-11-05 11:54 UTC, somnevaetsya commented on internal/repository/vacancy.go
> +func (vp *VacancyPostgres) Update(userId uint, vacancyId int, vacancy *models.UpdateVacancy) error {
А лучше принимать одинаковые параметры в модели, если это там происходит. Если нет, то рил кастим к одному типу

2022-11-05 11:54 UTC, somnevaetsya commented on internal/repository/vacancy.go
> +	userIdString := strconv.FormatUint(uint64(userId), 10)
Это бизнес-логика, в юзкейс

2022-11-05 11:54 UTC, somnevaetsya commented on internal/repository/vacancy_activity.go
> +	apply.UserAccountId = userId
Это бизнес-логика, в юзкейс

2022-11-05 11:54 UTC, somnevaetsya commented on internal/repository/vacancy_activity.go
> +	return applies, validation.QueryVacancyValidation(query)
Вот эта валидация вводит меня в заблуждение, расскажи, пожалуйста, почему так

2022-11-05 21:51 UTC, AkimEgorov commented on internal/entity/models/vacancy.go
>  type Vacancy struct {
Новые поля меня Влад попросил добавить. Эму они нужны

2022-11-05 21:54 UTC, AkimEgorov commented on internal/entity/models/vacancyActivity.go
>  type VacancyActivity struct {
Да

2022-11-22 19:52 UTC, closed without merging