Integration
go-park-mail-ru/2022_2_Technopanki pull request #22
Opened 2022-11-08 20:36 UTC by Zuhropenchik

2022-11-15 17:18 UTC, somnevaetsya commented on internal/entity/constants/user.go
> +package constants
Тоже можно положить к пользователю

2022-11-15 17:20 UTC, somnevaetsya commented on internal/entity/validation/resume.go
> +package validation
Можно было бы закинуть к модели

2022-11-15 17:21 UTC, somnevaetsya commented on internal/entity/validation/resume_test.go
> +func Test_ResumeValidaion(t *testing.T) {
Копец, что ты тестируешь....

2022-11-15 17:22 UTC, somnevaetsya commented on internal/entity/validation/user.go
>  	if strings.Count(user.Email, "@") != 1 {
А если собак больше?

2022-11-15 17:22 UTC, somnevaetsya commented on internal/entity/validation/resume.go
> +package validation
Не, не надо

2022-11-15 17:23 UTC, somnevaetsya commented on internal/errorHandler/errorHandler.go
> +	ErrResumeNotFound              = errors.New("resume not found")
Давай приведем к единообразию - либо пишем по-русски, либо по-английски, большая буква также

2022-11-15 17:27 UTC, somnevaetsya commented on internal/network/handlers/handler.go
>  )
Или допустим, все интерфейсы остаются тут, а создадим папку impl, в которой будут имплементации всех интерфейсов

2022-11-15 17:28 UTC, somnevaetsya commented on internal/network/handlers/resume.go
> +	if userIdFromContext != uint(userId) {
Кусок бизнелогики по факту...

2022-11-15 17:29 UTC, somnevaetsya commented on internal/network/handlers/resume.go
> +	if userIdFromContext != uint(userId) {
Тоже кусок бизнеслогики

2022-11-15 17:31 UTC, somnevaetsya commented on internal/network/handlers/resume.go
> +	userType, getTypeErr := rh.userHandler.GetUserType(c)
Воот это вообще не понял, у нас хендлеры отвечают за прием/отправку данных, а тут еще и используется другой хендлер. Это бизнеслогика конкретная, хендлеры только принимают/возвращают данные

2022-11-15 17:31 UTC, somnevaetsya commented on internal/network/handlers/resume.go
> +	isAccessAllowed := rh.isResumeAvailable(c, uint(id))
Это бизнеслогика

2022-11-15 17:31 UTC, somnevaetsya commented on internal/network/handlers/resume.go
> +	isAccessAllowed := rh.isResumeAvailable(c, uint(id))
Это бизнеслогика

2022-11-15 17:34 UTC, somnevaetsya commented on internal/network/handlers/utils.go
> +func (rh *ResumeHandler) isResumeAvailable(c *gin.Context, id uint) error {
Бизнеслогика

2022-11-15 17:35 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +type getAllVacanciesResponcePointer struct {
А зачем нам две почти одинаковые структуры?

2022-11-15 17:35 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +	c.JSON(http.StatusOK, getAllVacanciesResponcePointer{
Чет не понимаю

2022-11-15 17:36 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +type statusResponse struct {
Можно же просто отдать http.StatusCode

2022-11-15 17:38 UTC, somnevaetsya commented on internal/network/response/user.go
> +		}
А если другое поле? Такое возможно?

2022-11-15 17:39 UTC, somnevaetsya commented on internal/network/router.go
> +				image.DELETE("/", sessionMW.Session, h.UserHandler.DeleteUserImage, middleware.ErrorHandler())
Не используется на фронте

2022-11-15 17:39 UTC, somnevaetsya commented on internal/repository/images/user.go
> +		fmt.Println("Error in file name/path (UploadUserAvatar)")
Отладочная печать

2022-11-15 17:39 UTC, somnevaetsya commented on internal/repository/images/user.go
> +			fmt.Printf("fail to sync file %s, error: %s", resultImage.Name(), errSync.Error())
Отладочная печать

2022-11-15 17:39 UTC, somnevaetsya commented on internal/repository/images/user.go
> +			fmt.Printf("fail to close file %s, error: %s", resultImage.Name(), errClose.Error())
Отладочная печать

2022-11-15 17:40 UTC, somnevaetsya commented on internal/repository/repository.go
> +		if query.Error.Error() == "record not found" {
Нельзя сравнивать их как строки, писал об этом точно, есть errors.Is()

2022-11-15 17:41 UTC, somnevaetsya commented on internal/repository/repository.go
>  func NewPostgresRepository(db *gorm.DB) *Repository {
Предлагаю так же, как и с хендлерми: каждый интерфейс в отдельном файле(необязательно), создаем папку impl, там реализация, также создаем папку mocks, там моки

2022-11-15 17:43 UTC, somnevaetsya commented on internal/repository/resume.go
> +	for _, elem := range result {
Просто посчитай, сколько ты запросов сделаешь к базе

2022-11-15 17:43 UTC, somnevaetsya commented on internal/repository/resume.go
> +	resume.UserAccountId = old.UserAccountId
Бизнес-логика

2022-11-17 14:06 UTC, Zuhropenchik commented on internal/usecases/usecase.go
> +	Delete(uint, int) error
Аналогичная просьба

2022-11-20 07:29 UTC, somnevaetsya requested changes
Близко к концу

2022-11-20 07:29 UTC, somnevaetsya commented on configs/config.go
> +	Security               SecurityConfig   `yaml:"security"`
Никто так и не ответил...

2022-11-20 07:29 UTC, somnevaetsya commented on internal/entity/utils/algorithm.go
> +package utils
Никто не поправил

2022-11-20 07:29 UTC, somnevaetsya commented on internal/entity/validation/user.go
>  	if strings.Count(user.Email, "@") != 1 {
done

2022-11-20 07:29 UTC, somnevaetsya commented on cmd/main.go
>  	handler := handlers.NewHandlers(useCase, &mainConfig, redisRepository)
Почему RedisRepository отдельно и прям напрямую? Так нельзя

2022-11-20 07:29 UTC, somnevaetsya commented on cmd/main.go
>  		redisRepository,
Почему RedisRepository особенный?

2022-11-20 07:29 UTC, somnevaetsya commented on cmd/main.go
> +		logrus.Fatal(configErr.Error())
Можно просто configErr

2022-11-20 07:29 UTC, somnevaetsya commented on cmd/main.go
> +	client, redisErr := repositorypkg.RedisConnect(&mainConfig.Redis)
RedisClient

2022-11-20 07:29 UTC, somnevaetsya commented on internal/entity/models/experienceDetail.go
> +	ExpDDescription string    `json:"description" gorm:"not null;"`
Не понимаю, что означает

2022-11-20 07:29 UTC, somnevaetsya commented on internal/errorHandler/errorHandler.go
>  )
Может мы сделаем отдельный пакет под ошибки в pkg? Что думаешь?

2022-11-20 07:29 UTC, somnevaetsya commented on internal/network/handlers/handler.go
> +	cfg                    *configs.Config
Воот это поле не используется

2022-11-20 07:29 UTC, somnevaetsya commented on internal/network/handlers/impl/user.go
> +	sessionRepo session.Repository
Мне не особо нравится, что мы прям напрямую засовываем его, может намутим юзкейс, чтобы прям чистая была?

2022-11-20 07:29 UTC, somnevaetsya commented on internal/network/middleware/CORSMiddleware.go
> +	config.AllowHeaders = []string{"Origin", "Content-Length", "Content-Type", "X-CSRF-Token"}
В конфиг не хотим?

2022-11-20 07:29 UTC, somnevaetsya commented on internal/repository/impl/resume.go
> +	query := rp.db.Table("resumes").
Вот тут по идее не должно быть 3 запроса, потому что сделал запрос, а потом три раза выбираешь в структуру поля

2022-11-20 07:29 UTC, somnevaetsya commented on internal/repository/impl/resume.go
> +	for i, elem := range result {
Бомба!

2022-11-20 07:29 UTC, somnevaetsya commented on internal/repository/impl/resume.go
> +	query := rp.db.Table("resumes").
Супер

2022-11-20 07:29 UTC, somnevaetsya commented on internal/repository/impl/resume.go
> +	query := rp.db.Model(&models.Resume{}).Select("vacancies.posted_by_user_id").
Хорош

2022-11-20 07:29 UTC, somnevaetsya commented on internal/repository/impl/vacancy.go
> +func (vp *VacancyPostgres) GetAuthor(email string) (*models.UserAccount, error) {
Не проще юзкейс подключить еще один?

2022-11-20 07:29 UTC, somnevaetsya commented on internal/repository/impl/vacancy_activity.go
> +	//var responce []*models.VacancyActivityResponce
Комментарии убираем

2022-11-20 07:29 UTC, somnevaetsya commented on internal/repository/impl/vacancy_activity.go
> +	//return queryValidation(query, "vacancy_activity")
Убираем комментарии

2022-11-20 07:29 UTC, somnevaetsya commented on internal/repository/images/user.go
> +
Нам это еще нужно?

2022-11-20 07:29 UTC, somnevaetsya commented on internal/usecases/impl/resume_test.go
> +
Чиним

2022-11-20 07:29 UTC, somnevaetsya commented on internal/usecases/impl/user.go
> +	sessionRepo session.Repository
Так вот сессионный репозиторий, зачем мы его в хендлер явно засовываем?

2022-11-20 07:29 UTC, somnevaetsya commented on internal/usecases/impl/user.go
> +	input.PublicFields = "email contact_number applicant_current_salary" //TODO после РК3 убрать для добавления фичи с доступом
Разделить - пробел?

2022-11-20 07:29 UTC, somnevaetsya commented on internal/usecases/impl/user.go
> +	if len(fields) == 1 && (fields[0] == "" || fields[0] == "null") {
Кто такой null? Как минимум, в константы и хочу объяснения

2022-11-22 18:29 UTC, somnevaetsya requested changes

2022-11-22 19:47 UTC, VladislavKirpichov approved these changes

2022-11-22 19:47 UTC, AkimEgorov approved these changes

2022-11-22 19:48 UTC, sonichka-s approved these changes

2022-11-22 19:50 UTC, somnevaetsya approved these changes

2022-11-22 19:50 UTC, merged