Обработка ошибок, авторизация, регистрация, сессии
go-park-mail-ru/2022_2_Technopanki pull request #5
Opened 2022-10-02 13:48 UTC by Zuhropenchik

2022-10-02 18:55 UTC, somnevaetsya requested changes

2022-10-02 18:55 UTC, somnevaetsya commented on data.go
> +var Vacancies = []entity.Vacancy{
Мало вакансий

2022-10-02 18:55 UTC, somnevaetsya commented on data.go
> +		ID:            "2",
Не пойдет, нужен реальный контент

2022-10-02 18:55 UTC, somnevaetsya commented on internal/entity/vacancy.go
> +	MinimalSalary int       `json:"minimal salary"`
Нижнее подчеркивание

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +		_ = c.Error(middleware.ErrBadRequest)
Вынести ошибки в отдельный пакет

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	user := storage.UserStorage.FindByEmail(input.Email)
Лучше возвращать еще одну ошибку и проверять ошибку, потому что на фронт приходит не пойми что

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password)); err != nil {
Можно сделать обертку, чтобы понятнее выглядело

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	c.SetCookie("session", token, int(sessions.SessionsStore.DefaultExpiresAt), "/", "localhost", false, true)
Можно сделать дополнительную сущность, которая будет отражать, что все нормально. Будем проставлять код 200 и сообщение, что все ок

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	user := storage.UserStorage.FindByEmail(input.Email)
Замечание насчет этой функции выше

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	c.JSON(http.StatusOK, gin.H{
Выпиливаем

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	token, err := c.Cookie("session")
У нас залогиненный пользователь, а значит, проходя через авторизационную мидлварь, должен проставиться его айдшиник/емайл, а значит, что нам нужно проверить, есть ли в контексте джина айдишник/емайл, то есть куку не надо проверять

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	c.SetCookie("session", token, -1, "/", "localhost", false, true)
Вернуть сущность, что все прошло нормально

2022-10-02 18:55 UTC, somnevaetsya commented on data.go
> +var Vacancies = []entity.Vacancy{
Почему не мапа? Поиск О(1) не нужен?

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +		for _, v := range jobflow.Vacancies {
Тут меняем на мапу и переписываем логику

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/middleware/errorHandler.go
> +package middleware
Выносим в другой пакет

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/middleware/errorHandler.go
> +			c.AbortWithStatusJSON(ConvertError(rawErr.Err), gin.H{"error:": rawErr.Error()})
Сущность под ошибки

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/middleware/session.go
> +	c.Set("cookie", "verification value")
Проставляем полезную информацию

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/router.go
> +	config := cors.DefaultConfig()
Это у нас в мидлвари, зачем второй раз?

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/sessions/store.go
> +func NewStore() Store {
Без конструкторов, пожалуйста

2022-10-02 18:55 UTC, somnevaetsya commented on internal/network/sessions/store.go
> +	return Session{}, errors.New("no session with this token")
Кастомная ошибка

2022-10-02 18:55 UTC, somnevaetsya commented on internal/storage/users.go
> +func (u *Users) FindByEmail(email string) entity.User {
Возврат ошибки

2022-10-02 18:55 UTC, somnevaetsya commented on internal/storage/users.go
> +	encryptedPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), 14)
Что за магическое число 14????

2022-10-02 18:55 UTC, somnevaetsya commented on internal/storage/users.go
> +	encryptedPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), 14)
Вынести в константы

2022-10-02 18:55 UTC, somnevaetsya commented on internal/storage/users.go
> +func NewUsersStorage() Users {
Опять конструктор....

2022-10-02 18:55 UTC, somnevaetsya commented on internal/entity/user.go
> +package entity
Проставить omitempty

2022-10-03 16:33 UTC, somnevaetsya commented on data.go
> +var Vacancies = []entity.Vacancy{
done

2022-10-03 16:34 UTC, somnevaetsya commented on data.go
> +		ID:            "2",
done

2022-10-03 16:34 UTC, somnevaetsya commented on internal/entity/vacancy.go
> +	MinimalSalary int       `json:"minimal salary"`
done

2022-10-03 16:34 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +		_ = c.Error(middleware.ErrBadRequest)
done

2022-10-03 16:35 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	user := storage.UserStorage.FindByEmail(input.Email)
done

2022-10-03 16:35 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password)); err != nil {
done

2022-10-03 16:35 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	c.SetCookie("session", token, int(sessions.SessionsStore.DefaultExpiresAt), "/", "localhost", false, true)
done

2022-10-03 16:35 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	user := storage.UserStorage.FindByEmail(input.Email)
done

2022-10-03 16:36 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	c.JSON(http.StatusOK, gin.H{
done

2022-10-03 16:36 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	token, err := c.Cookie("session")
Не исправлено

2022-10-03 16:36 UTC, somnevaetsya commented on internal/network/handlers/auth.go
> +	c.SetCookie("session", token, -1, "/", "localhost", false, true)
done

2022-10-03 16:37 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +		for _, v := range jobflow.Vacancies {
done

2022-10-03 16:37 UTC, somnevaetsya commented on internal/network/middleware/errorHandler.go
> +package middleware
done

2022-10-03 16:37 UTC, somnevaetsya commented on internal/network/middleware/errorHandler.go
> +			c.AbortWithStatusJSON(ConvertError(rawErr.Err), gin.H{"error:": rawErr.Error()})
done

2022-10-03 16:38 UTC, somnevaetsya commented on internal/network/router.go
> +	config := cors.DefaultConfig()
done

2022-10-03 16:38 UTC, somnevaetsya commented on internal/network/sessions/store.go
> +	return Session{}, errors.New("no session with this token")
done

2022-10-03 16:39 UTC, somnevaetsya commented on internal/storage/users.go
> +func (u *Users) FindByEmail(email string) entity.User {
done

2022-10-03 16:39 UTC, somnevaetsya commented on internal/storage/users.go
> +	encryptedPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), 14)
done

2022-10-03 16:39 UTC, somnevaetsya commented on internal/storage/users.go
> +func NewUsersStorage() Users {
done

2022-10-03 16:40 UTC, somnevaetsya commented on cmd/main.go
> +	RunErr := router.Run("localhost:8080")
Зачем с большой буквы? Куда-то импортируете?

2022-10-03 16:41 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +		return errorHandler.InvalidValidatePattern
Абсолютно непонятная ошибка

2022-10-03 16:42 UTC, somnevaetsya commented on internal/errorHandler/errorHandler.go
> +	InvalidUserName        = errors.New("invalid user name")
Ошибки реально непонятные, а почему инвалид? да просто так, инвалид и все. А на фронте сиди и локти кусай, почему так

2022-10-03 16:43 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +		if elem, ok := jobflow.Vacancies[id]; ok {
А если у нас нет такой вакансии, что делать?

2022-10-03 16:44 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +//func PostVacancy(c *gin.Context) {
Зачем артефакты?

2022-10-03 16:44 UTC, somnevaetsya commented on internal/network/middleware/session.go
> +	c.Set("userID", userSession.Email)
Нормально-нормально

2022-10-03 16:45 UTC, somnevaetsya commented on internal/network/sessions/store.go
> +	return Session{}, errorHandler.ErrNoSuitableSession
Нет подходящей сессии? Это как?

2022-10-03 16:46 UTC, somnevaetsya commented on internal/storage/users.go
> +var COST = 10
Ну хотя бы комментарий какой-то, я так и не могу понять, что за магия

2022-10-04 19:42 UTC, somnevaetsya commented on cmd/main.go
> +	RunErr := router.Run("localhost:8080")
done

2022-10-04 19:42 UTC, somnevaetsya commented on data.go
> +		Description:   "Группа Компаний «**********» открывает набор на позицию Middle Golang разработчик, в сильный и амбициозный коллектив. Мы - финтех компания, которая разработала платежный шлюз, работ
done

2022-10-04 19:42 UTC, somnevaetsya commented on internal/entity/validation/user.go
> +		return errorHandler.InvalidValidatePattern
done

2022-10-04 19:43 UTC, somnevaetsya commented on internal/errorHandler/errorHandler.go
> +	InvalidUserName        = errors.New("invalid user name")
done

2022-10-04 19:43 UTC, somnevaetsya commented on internal/network/handlers/vacancy.go
> +//func PostVacancy(c *gin.Context) {
done

2022-10-04 19:44 UTC, somnevaetsya commented on internal/network/middleware/session.go
> +	c.Set("userID", userSession.Email)
done

2022-10-04 19:44 UTC, somnevaetsya commented on internal/network/sessions/store.go
> +	return Session{}, errorHandler.ErrNoSuitableSession
done

2022-10-05 10:01 UTC, VladislavKirpichov approved these changes

2022-10-05 10:08 UTC, AkimEgorov approved these changes

2022-10-05 10:35 UTC, somnevaetsya approved these changes

2022-10-05 10:35 UTC, merged