Favorite vacancies
go-park-mail-ru/2022_2_Technopanki pull request #58
Opened 2022-12-09 19:23 UTC by AkimEgorov

2022-12-10 08:45 UTC, z-urvancev requested changes

2022-12-10 08:45 UTC, z-urvancev commented on internal/network/handlers/impl/user.go
>  			split := strings.Split(search, " ")
Contains нужно оставить

2022-12-10 16:38 UTC, somnevaetsya requested changes
Молодца, мне нравится) Надеюсь, что еще и работает)

2022-12-10 16:38 UTC, somnevaetsya commented on internal/network/handlers/impl/user.go
>  			split := strings.Split(search, " ")
Зачем?

2022-12-10 16:38 UTC, somnevaetsya commented on internal/network/handlers/impl/vacancy.go
> +	addErr := vh.vacancyUseCase.AddVacancyToFavorites(email, uint(id))
Можно переиспользовать переменную, `err = `

2022-12-10 16:38 UTC, somnevaetsya commented on internal/network/handlers/impl/vacancy.go
> +	vacancies, GetErr := vh.vacancyUseCase.GetUserFavoriteVacancies(email)
Чего переменная с большой буквы?

2022-12-10 16:38 UTC, somnevaetsya commented on internal/network/handlers/impl/vacancy.go
> +	deleteErr := vh.vacancyUseCase.DeleteVacancyFromFavorites(email, uint(id))
Есть переменная err, давай ее сюда `err = `

2022-12-10 16:38 UTC, somnevaetsya commented on internal/network/router.go
> +			vacancies.GET("/favorites/", h.VacancyHandler.GetUserFavoriteVacancies, errorHandler.Middleware())
В конце / не надо

2022-12-13 07:07 UTC, somnevaetsya requested changes
Остались неисправленные замечания

2022-12-13 07:07 UTC, somnevaetsya commented on internal/network/handlers/impl/user.go
>  			split := strings.Split(search, " ")
Никто так и не поправил((

2022-12-13 07:07 UTC, somnevaetsya commented on internal/network/handlers/impl/vacancy.go
> +	deleteErr := vh.vacancyUseCase.DeleteVacancyFromFavorites(email, uint(id))
Тоже((

2022-12-13 17:48 UTC, AkimEgorov commented on internal/network/handlers/impl/user.go
>  			split := strings.Split(search, " ")
Я не стал его возвращать, потому что не вижу смысла. Захар говорил, что без него не проходит линтер, но вроде все ок

2022-12-17 20:00 UTC, somnevaetsya requested changes
Один тест-кейс остался, надо поправить

2022-12-21 19:08 UTC, somnevaetsya approved these changes

2022-12-21 19:08 UTC, merged