Resume in pdf
go-park-mail-ru/2022_2_Technopanki pull request #60
Opened 2022-12-10 18:34 UTC by VladislavKirpichov

2022-12-18 16:37 UTC, somnevaetsya requested changes
Ребейз....

2022-12-18 16:37 UTC, somnevaetsya commented on .github/workflows/deploy.yml
> +name: Deploy
Походу нужен ребейз, этого файла не должно быть здесь

2022-12-18 16:37 UTC, somnevaetsya commented on Dockerfile-auth
> +COPY --from=builder /auth/.env /auth/.env
Этого вроде тоже

2022-12-18 16:37 UTC, somnevaetsya commented on auth_microservice/configs/config.go
> +	envErr := godotenv.Load(".env")
Да и вот этого тоже

2022-12-18 16:37 UTC, somnevaetsya commented on internal/network/handlers/impl/resume.go
> +	resumeStyle, exists := themes.ThemesMap[style]
Бомба

2022-12-18 16:37 UTC, somnevaetsya commented on internal/network/handlers/impl/user_test.go
> +			expectedResponseBody: "{\"id\":0,\"user_type\":\"applicant\",\"email\":\"test@gmail.com\",\"password\":\"\",\"contact_number\":\"\",\"status\":\"\",\"description\":\"\",\"image\":\"\",\"average_co
Ну не должно быть здесь((((

2022-12-18 16:37 UTC, somnevaetsya commented on internal/repository/images/user.go
> +func Average(img image.Image) string {
Да и этого не должно быть

2022-12-18 16:37 UTC, somnevaetsya commented on internal/usecases/utils/utils.go
> +		Crop:                   imagepkg.Rectangle{},
Вроде пустая структура, нам не надо

2022-12-18 16:37 UTC, somnevaetsya commented on internal/usecases/utils/utils.go
> +		BypassFiltering:        false,
Тут много дефолтные значений, давай их уберем, оставим те, которые не равны дефолтным

2022-12-18 16:37 UTC, somnevaetsya commented on internal/usecases/utils/utils.go
> +		return []byte{}, err
Как насчет nil, err?

2022-12-18 16:37 UTC, somnevaetsya commented on pkg/errorHandler/errorHandler.go
> +	// TODO
Каков туду?

2022-12-18 16:37 UTC, somnevaetsya commented on pkg/themes/themes.go
> +var ThemesMap = map[string]string{
Хочу демонстрацию в личку....

2022-12-18 16:37 UTC, somnevaetsya commented on vault/envGen.go
> +package main
Это тоже не твое, надо убирать

2022-12-18 18:30 UTC, z-urvancev requested changes

2022-12-18 18:30 UTC, z-urvancev commented on .env
> +TOKEN=asfsfasfasdfasf
Пустая строка)

2022-12-18 18:30 UTC, z-urvancev commented on cmd/main.go
> +
Опять откуда-то вылезло

2022-12-18 18:30 UTC, z-urvancev commented on internal/network/response/user.go
> -			result.TwoFactorSignIn = user.TwoFactorSignIn
Аналогично

2022-12-18 18:30 UTC, z-urvancev commented on internal/repository/images/user.go
> +	//}
Раскомментить

2022-12-18 18:30 UTC, z-urvancev commented on test.go
> +}
Удалить

2022-12-18 18:30 UTC, z-urvancev commented on vault/envGen.go
> +
??

2022-12-18 18:31 UTC, z-urvancev commented on .env
> +TOKEN=asfsfasfasdfasf
И ПОЧЕМУ ЭТОГО ФАЙЛА НЕТ В ИГНОРЕ

2022-12-19 20:42 UTC, somnevaetsya requested changes

2022-12-19 20:42 UTC, somnevaetsya commented on Dockerfile
> +FROM golang:alpine as builder
Это уже не нужно, посмотри, как работает то, что сейчас в мастере

2022-12-19 20:42 UTC, somnevaetsya commented on internal/usecases/utils/utils.go
> +type ResumeTemplate struct {
Вроде используется только в этом пакете, может сделаем приватным?

2022-12-19 20:42 UTC, somnevaetsya commented on internal/usecases/utils/utils.go
> +	page.FooterFontSize.Set(10)
Идеально бы в конфиг или вообще в параметры

2022-12-19 20:42 UTC, somnevaetsya commented on internal/usecases/utils/utils.go
> +	page.FooterFontSize.Set(10)
В параметры запроса

2022-12-21 19:17 UTC, somnevaetsya requested changes

2022-12-21 19:17 UTC, somnevaetsya commented on internal/network/router.go
> +			vacancies.POST("/favorites/:id", sessionMW.Session, h.VacancyHandler.AddVacancyToFavorites, errorHandler.Middleware())
Это не должно быть у тебя

2022-12-21 19:17 UTC, somnevaetsya commented on internal/repository/impl/vacancy.go
> +func (vp *VacancyPostgres) AddVacancyToFavorites(user *models.UserAccount, vacancy *models.Vacancy) error {
Это не твое

2022-12-21 19:17 UTC, somnevaetsya commented on internal/repository/repository.go
> +	AddVacancyToFavorites(user *models.UserAccount, vacancy *models.Vacancy) error
Это не твое

2022-12-21 19:17 UTC, somnevaetsya commented on internal/usecases/impl/user.go
> +		TwoFactorSignIn: oldUser.TwoFactorSignIn, Description: oldUser.Description, AverageColor: user.AverageColor})
Тоже не твое

2022-12-21 19:17 UTC, somnevaetsya commented on internal/usecases/impl/vacancy.go
> +func (vs *VacancyService) AddVacancyToFavorites(email string, vacancyId uint) error {
Не твое

2022-12-21 19:17 UTC, somnevaetsya commented on internal/usecases/impl/vacancy_test.go
> +func TestVacancyService_AddVacancyToFavorites(t *testing.T) {
Это не твое

2022-12-21 20:07 UTC, somnevaetsya approved these changes

2022-12-21 20:07 UTC, merged