Рассылка
go-park-mail-ru/2022_2_Technopanki pull request #64
Opened 2022-12-19 16:39 UTC by z-urvancev

2022-12-19 19:07 UTC, somnevaetsya requested changes

2022-12-19 19:07 UTC, somnevaetsya commented on internal/repository/images/user.go
> +	//fullPath := strings.Join([]string{cfg.Path, "avatar/"}, "")
Я не смотрю дальше

2022-12-21 19:13 UTC, somnevaetsya requested changes
Убрать лого

2022-12-21 19:13 UTC, somnevaetsya commented on internal/usecases/mail/grpc.go
> +	if len(vacancies) < 5 || len(emails) == 0 {
То есть если меньше 5, то ничего не отсылаем?

2022-12-21 19:13 UTC, somnevaetsya commented on mail_microservice/usecase/impl/mail.go
> +			log.Printf("error with send to %s: %s", email, err)
Ошибку просто игнорируем?

2022-12-21 19:13 UTC, somnevaetsya commented on mail_microservice/usecase/impl/mail.go
> +			log.Printf("error with send to %s: %s", email, err)
Ошибку просто игнорируем?

2022-12-21 22:35 UTC, z-urvancev commented on mail_microservice/usecase/impl/mail.go
> +			log.Printf("error with send to %s: %s", email, err)
Да, пускай просто не присылает и выводит ошибку, а не прерывает всю функцию.

2022-12-23 16:39 UTC, somnevaetsya commented on internal/network/handlers/impl/user.go
> +	fmt.Println("user in handler: ", input)
Спасибо за дебаг

2022-12-23 16:45 UTC, somnevaetsya approved these changes

2022-12-23 16:47 UTC, merged